### ISSUE TITLE
[feature] Undici pool suppport.

### ISSUE THREAD

**Issue by SkeLLLa** [kibertoad/undici-retry#18]
Hi. Alongside with `Client` undici has `Pool`. It has pretty much similar interface with `Client`. So likely adding type `Pool` to `sendWithRetry` call first argument will make it compatible with undici pools as well.

WDYT?

PS: Or maybe it's better to create an interface like `IClientLike` which will only require `request` function that is actually used under the hood. Then either `Client`, `Pool` or other thing could be passed.

**Comment by kibertoad** [comment]
@SkeLLLa sounds great! can you send a PR?

**Comment by SkeLLLa** [comment]
Yep. Will do tomorrow.

**Comment by kibertoad** [comment]
thanks!
